name: Lint
on: push
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn install --frozen-lockfile
    - name: Run Lint
      run: yarn lint --max-warnings 1